# Generated by Django 5.0.1 on 2024-02-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='precio_venta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
