# Generated by Django 5.0.1 on 2024-02-04 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_articulos_precio_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cotizacion', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('lugar', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('vendedor', models.CharField(max_length=100)),
                ('receptor_cotizacion', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('forma_pago', models.CharField(max_length=50)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_producto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestionPedidos.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.articulos')),
            ],
        ),
    ]
