# Generated by Django 5.0.1 on 2024-02-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_cotizacion_detallecotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='cotizacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='gestionPedidos.cotizacion'),
        ),
    ]
