# Generated by Django 5.0.1 on 2024-02-04 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_articulos_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='cotizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='gestionPedidos.cotizacion'),
        ),
    ]
