# Generated by Django 5.0.1 on 2024-02-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0008_alter_articulos_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
    ]
