# Generated by Django 5.0.1 on 2024-02-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0012_alter_articulos_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecotizacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='total_producto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
