# Generated by Django 5.0.1 on 2024-02-04 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0013_alter_detallecotizacion_precio_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='cotizacion',
        ),
    ]
