# Generated by Django 5.0.1 on 2024-02-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0014_remove_articulos_cotizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecotizacion',
            old_name='producto',
            new_name='articulo',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='numero_contacto',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='forma_pago',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='receptor_cotizacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='articulos',
            name='contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='articulos',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='empresa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='lugar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='seccion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='vendedor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='total_producto',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
