# Generated by Django 5.0.1 on 2024-02-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0015_rename_producto_detallecotizacion_articulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='articulo',
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
        migrations.DeleteModel(
            name='DetalleCotizacion',
        ),
    ]
