# Generated by Django 5.0.1 on 2024-02-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0016_remove_detallecotizacion_cotizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='hora',
        ),
    ]
