# Generated by Django 5.0.1 on 2024-02-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0021_remove_articulos_cotizacion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='descripcion',
        ),
    ]
