# Generated by Django 5.0.2 on 2024-02-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0023_remove_articulos_nombre_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
