# Generated by Django 5.0.1 on 2024-02-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0024_alter_articulos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='numero_boleta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Boleta'),
        ),
    ]
