# Generated by Django 5.0.2 on 2024-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0026_delete_clientes_delete_pedidos_delete_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='aprobado',
            field=models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20, null=True, verbose_name='Aprobado/Rechazado'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
    ]
