# Generated by Django 5.0.2 on 2024-03-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0031_alter_tarea_asignadas_alter_tarea_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(default='Sin Movimiento', max_length=200),
        ),
    ]
