# Generated by Django 5.0.2 on 2024-03-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0032_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='cantidad',
            field=models.IntegerField(blank=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Valor Unitario'),
        ),
    ]
