# Generated by Django 5.0.2 on 2024-03-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0033_alter_articulos_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitario'),
        ),
    ]
