# Generated by Django 5.0.2 on 2024-05-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0034_alter_articulos_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa_nucleo', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_empresa', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('contacto_empresa', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
